experiments: 

###################
# FULLY CONN EXPERIMENTS
##################
  - name: FULL_01
    data: bsds
    sim_matrix: fcn-rbf

  - name: FULL_01
    data: bsds
    sim_matrix: fcn-laplacian

###################
# KNN EXPERIMENTS 
##################
  - name: KNN_01
    data: bsds
    sim_matrix: knn10


